################################### English language #####################################
languageName = "En"
languageCode = "en-us"
contentDir = "content/en"
weight = 20
# copyright
copyright = "Designed By [Themefisher](https://themefisher.com/) & Developed By [Gethugothemes](https://gethugothemes.com/)"

###################################### Navigation ######################################
# homepage section menu
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Products"
url = "products"
weight = 2

[[menu.main]]
name = "Blog"
url = "blog"
weight = 3

[[menu.main]]
name = "Review"
pre = "#"
url = "testimonial"
weight = 4

[[menu.main]]
name = "Contact"
url = "contact"
weight = 5

# footer menu
[[menu.footer]]
name = "Blog"
url = "blog"
weight = 1

[[menu.footer]]
name = "Contact"
url = "contact"
weight = 2

[[menu.footer]]
name = "Terms & Conditions"
url = "terms-conditions"
weight = 3

[[menu.footer]]
name = "Privacy Policy"
url = "privacy-policy"
weight = 4
